routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\Slider\SliderListController;
use App\Http\Controllers\Admin\Slider\SliderTrashListController;
use App\Http\Controllers\Admin\Slider\SliderTrashController;
use App\Http\Controllers\Admin\Slider\SliderEditController;
use App\Http\Controllers\Admin\Slider\SliderUpdateController;
use App\Http\Controllers\Admin\Slider\SliderDeleteController;
use App\Http\Controllers\Admin\Slider\SliderRestoreController;
use App\Http\Controllers\Admin\Slider\SliderCreationController;
use App\Http\Controllers\Admin\Slider\SliderStoreController;
use App\Http\Controllers\Admin\Slider\DeleteAllSliderController;
use App\Http\Controllers\Admin\Slider\DeleteAllTrashedSliderController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('',HomeController::class)->name('home');

Route::prefix('admin')
        ->name('admin.')
        ->group(function (){

            Route::name('slider.')
                    ->prefix('slider')
                    ->group(function (){
                        Route::get('',SliderListController::class)->name('home');
                        Route::get('/trash',SliderTrashListController::class)->name('trash-list');
                        Route::Delete('/trash/{id}',SliderTrashController::class)->name('trash-slide');
                        Route::get('/edit/{id}',SliderEditController::class)->name('edit');
                        Route::put('/edit/{id}',SliderUpdateController::class)->name('update');
                        Route::delete('/delete/{id}',SliderDeleteController::class)->name('delete-slide');
                        Route::get('/restore/{id}',SliderRestoreController::class)->name('restore-slide');
                        Route::get('create',SliderCreationController::class)->name('create-slide');
                        Route::post('create',SliderStoreController::class)->name('store-slide');
                        Route::delete('delete-all',DeleteAllSliderController::class)->name('delete-all-sliders');
                    });

        });

app/Models/Slider.php
<?php

namespace App\Models;

use App\Models\Scopes\WhereActiveIsTrueScope;
use App\Traits\Model\DisableTimeStampTrait;
use App\Traits\Model\Scope\WhereActive;
use App\Traits\Model\Scope\WhereActiveIsFalse;
use App\Traits\Model\Scope\WhereActiveIsTrue;
use Hekmatinasser\Verta\Verta;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Slider extends Model
{
    use HasFactory , DisableTimeStampTrait , SoftDeletes ;
    use WhereActive , WhereActiveIsTrue , WhereActiveIsFalse ;
    public function getJalaliCreatedAtAttribute():Verta|null {
        if (!isset($this->attributes['created_at']))
            return null;
        return verta($this->getAttribute('created_at'));
    }
    public function getJalaliUpdatedAtAttribute():Verta|null {
        if (!isset($this->attributes['updated_at']))
            return null;
        return verta($this->getAttribute('updated_at'));
    }
    public function getJalaliDeletedAtAttribute():Verta|null {
        if (!isset($this->attributes['deleted_at']))
            return null;
        return verta($this->getAttribute('deleted_at'));
    }
}

app/Http/Controllers/Admin/Slider/DeleteAllSliderController.php
<?php

namespace App\Http\Controllers\Admin\Slider;

use App\Http\Controllers\Controller;
use App\Services\DeleteAllSliderBuilder;
use App\Services\SliderThumbnailRemover;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\Request;

class DeleteAllSliderController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(DeleteAllSliderBuilder $builder)
    {
        $query = $builder->build();
        $thumbnails = $query->get(['thumbnail']);
        $deleted = $query->forceDelete();
        $messageKey = 'messages.ok';
        $message = $deleted.' slides successfully deleted !!!';
        if (!($deleted>0))
            return redirect()->route('admin.slider.home')->with($messageKey,[$message]);
        foreach ($thumbnails->all() as $thumbnail)
            if (!is_null($thumbnail->thumbnail))
                SliderThumbnailRemover::remove($thumbnail->thumbnail);
        return redirect()->route('admin.slider.home')->with($messageKey,[$message]);
    }
}

app/Http/Controllers/Admin/Slider/SliderCreationController.php
<?php

namespace App\Http\Controllers\Admin\Slider;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class SliderCreationController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(Request $request):View
    {
        return \view('pages.admin.slider.create');
    }
}

app/Http/Controllers/Admin/Slider/SliderDeleteController.php
<?php

namespace App\Http\Controllers\Admin\Slider;

use App\Http\Controllers\Controller;
use App\Services\DeleteSliderBuilder;
use App\Services\SliderThumbnailRemover;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class SliderDeleteController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(Request $request,int $id , DeleteSliderBuilder $builder)
    {
        $slide = $builder->build();
        if (is_null($slide))
            abort(404);
        $deleted = $slide->forceDelete();

        if ($deleted and !is_null($slide->thumbnail))
            SliderThumbnailRemover::remove($slide->thumbnail);

        $messageKey = 'messages.ok';
        $message = "slider with id $id has been successfuly Delete";
        if (!$deleted){
            $messageKey = 'messages.fail';
            $message = "slider with id $id no delete";
        }
        return back()->with($messageKey,[$message]);
    }
}

app/Http/Controllers/Admin/Slider/SliderEditController.php
<?php

namespace App\Http\Controllers\Admin\Slider;

use App\Http\Controllers\Controller;
use App\Repositories\SliderEditRepository;
use Illuminate\Http\Request;

class SliderEditController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(SliderEditRepository $editRepository, int $id)
    {
        $data = $editRepository->getData();
        if (is_null($data['slide']))
            abort(404);
        return view('pages.admin.slider.edit',$data);
    }
}

app/Http/Controllers/Admin/Slider/SliderListController.php
<?php

namespace App\Http\Controllers\Admin\Slider;

use App\Http\Controllers\Controller;
use App\Repositories\SliderIndexRepository;
use App\Services\SliderListBuilder;
use Illuminate\Http\Request;

class SliderListController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(SliderIndexRepository $indexRepository)
    {
        return view('pages.admin.slider.list',$indexRepository->getData());
    }
}

app/Http/Controllers/Admin/Slider/SliderRestoreController.php
<?php

namespace App\Http\Controllers\Admin\Slider;

use App\Http\Controllers\Controller;
use App\Services\RestoreSliderBuilder;
use Illuminate\Http\Request;

class SliderRestoreController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(int $id , Request $request , RestoreSliderBuilder $builder)
    {
        $slide = $builder->build();
        if (is_null($slide))
            abort(404);
        $restored = $slide->restore();
        $messageKey = 'messages.ok';
        $message = "slider with id $id has been successfuly restored from trash ";
        if (!$restored){
            $messageKey = 'messages.fail';
            $message = "slider with id $id no restore from trash";
        }
        return redirect()->route('admin.slider.trash-list')->with($messageKey,[$message]);
    }
}

app/Http/Controllers/Admin/Slider/SliderStoreController.php
<?php

namespace App\Http\Controllers\Admin\Slider;

use App\Http\Controllers\Controller;
use App\Http\Requests\SliderStoreRequest;
use App\Models\Slider;
use App\Services\SliderThumbnailUploader;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class SliderStoreController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(SliderStoreRequest $request , Slider $slider)
    {
        $slider->title = $request->get('title');
        $slider->description = $request->get('description');
        $slider->description = $request->get('description');
        if($request->hasFile('thumbnial')){
            $uploaded = SliderThumbnailUploader::upload($request);
            $slider->thumbnail = $uploaded->getPathname();
        }
        $slider->is_active = $request->has('is_active');
        $slider->created_at = Carbon::now();
        $saved = $slider->Save();
        $messageKey = 'messages.fail';
        $message = "fail make slider";
        if ($saved){
            $messageKey = 'messages.ok';
            $message = "slider with id {$slider->id} has been successfuly Created";
        }
        return redirect()->route('admin.slider.home')->with($messageKey,[$message]);
    }
}

app/Http/Controllers/Admin/Slider/SliderTrashController.php
<?php

namespace App\Http\Controllers\Admin\Slider;

use App\Http\Controllers\Controller;
use App\Services\TrashSliderBuilder;
use Illuminate\Http\Request;

class SliderTrashController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke( int $id, Request $request , TrashSliderBuilder $builder)
    {
        $slider = $builder->build();
        if (is_null($slider))
            abort(404);
        $deleted = $slider->delete();
        $messageKey = 'messages.ok';
        $message = "slider with id $id has been successfuly moved to trash";
        if (!$deleted){
            $messageKey = 'messages.fail';
            $message = "slider with id $id no moved to trash";
        }
        return back()->with($messageKey,[$message]);
    }
}

app/Http/Controllers/Admin/Slider/SliderTrashListController.php
<?php

namespace App\Http\Controllers\Admin\Slider;

use App\Http\Controllers\Controller;
use App\Repositories\SliderTrashListRepository;
use Illuminate\Http\Request;

class SliderTrashListController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(Request $request,SliderTrashListRepository $sliderTrashListRepository)
    {
        return view('pages.admin.slider.trash-list',$sliderTrashListRepository->getData());
    }
}

app/Http/Controllers/Admin/Slider/SliderUpdateController.php
<?php

namespace App\Http\Controllers\Admin\Slider;

use App\Http\Controllers\Controller;
use App\Http\Requests\SliderUpdateRequest;
use App\Services\SliderThumbnailRemover;
use App\Services\SliderThumbnailUploader;
use App\Services\UpdateSliderBuilder;
use Carbon\Carbon;
use Illuminate\Http\Request;

class SliderUpdateController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(SliderUpdateRequest $request, UpdateSliderBuilder $updateSliderBuilder ,int $id)
    {
        $slide = $updateSliderBuilder->build();
        if (is_null($slide))
            abort(404);
        $hasThumbnail = $request->hasFile('thumbnial');
        $slide->title = $request->title;
        $slide->description = $request->description ;
        $slide->is_active = $request->has('is_active');

        if ($hasThumbnail) {
            if(!is_null($slide->thumbnail))
                $oldTumbnail = $slide->thumbnail;
            $moved  = SliderThumbnailUploader::upload($request);
            $slide->thumbnail = $moved->getPathname();
        }
        $slide->updated_at = Carbon::now();
        $updated = $slide->update();

        if ($updated and isset($oldTumbnail))
            SliderThumbnailRemover::remove($oldTumbnail);

        $messageKey = 'messages.ok';
        $message = "slider with id $id has been successfuly updated";
        if (!$updated){
            $messageKey = 'messages.fail';
            $message = "slider with id $id no updated";
        }
        return redirect()->route('admin.slider.home')->with($messageKey,[$message]);
    }
}

resources/views/pages/admin/slider/create.blade.php
@extends('layouts.master')
@section('title')
@parent | create new slider
@endsection
@section('body')
    @component('components.errorBagPrinter')
    @endcomponent
    <form action="{{route('admin.slider.store-slide')}}" method="POST" enctype="multipart/form-data">
        @csrf
        @component('components.form-error-printer',['field' => 'title'])
        @endcomponent
        <label for="title">title</label>
        <input type="text" name="title" value="{{ old('title')}}" id="title">
        <hr>
        @component('components.form-error-printer',['field' => 'description'])
        @endcomponent
        <label for="description">description</label>
        <textarea id="description" name="description">
        {{old('description')}}
    </textarea>
        <hr>
        @component('components.form-error-printer',['field' => 'thumbnial'])
        @endcomponent
        <label for="thumbnail">thumbnail</label>
        <input type="file" name="thumbnial" id="thumbnail">
        <hr>
        @component('components.form-error-printer',['field' => 'active'])
        @endcomponent
        <label for="active">active</label>
        <input type="checkbox" name="is_active" @checked(old('is_active'))>
        <hr>
        <button type="submit"> save </button>
    </form>
@endsection

resources/views/pages/admin/slider/edit.blade.php
@extends('layouts.master')
@section('title')
    @parent | {{$title}}
@endsection

@section('body')
@component('components.errorBagPrinter') @endcomponent
<form action="{{ route('admin.slider.update',request()->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')

    @component('components.form-error-printer',['field' => 'title'])
    @endcomponent
    <label for="title">title</label>
    <input type="text" name="title" value="{{ old('title',$slide->title)}}" id="title">
    <hr>
    @component('components.form-error-printer',['field' => 'description'])
    @endcomponent
    <label for="description">description</label>
    <textarea id="description" name="description">
        {{old('description', $slide->description)}}
    </textarea>
    <hr>
    @component('components.form-error-printer',['field' => 'thumbnial'])
    @endcomponent
    <label for="thumbnail">thumbnail</label>
    <input type="file" name="thumbnial" id="thumbnail">
    @if(!is_null($slide->thumbnail))
        <img src="{{asset($slide->thumbnail)}}" style="width: 200px ; height: 200px">
    @else
        <h6 style="color: darkred"> has no thumbnail</h6>
    @endif
    <hr>
    @component('components.form-error-printer',['field' => 'active'])
    @endcomponent
    <label for="active">active</label>
    <input type="checkbox" name="is_active" @checked(old('is_active',$slide->is_active))>
    <hr>
    <button type="submit">update</button>
</form>
@endsection

resources/views/pages/admin/slider/list.blade.php
@php
    /** @var \Illuminate\Pagination\LengthAwarePaginator $slides */
    $verta = verta();
@endphp
@extends('layouts.master')
@section('title')
    @parent | {{$title}}
@endsection
@section('body')
    @include('partials.message-printer')
    @if($slides->isNotEmpty())
        <h4>total : {{$slides->total()}}</h4>
        <section class="actions">
            <form action="{{route('admin.slider.delete-all-sliders')}}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit">Delete</button>
            </form>
        </section>
        <section class="content">
            <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>thumbnail</th>
                    <th>title</th>
                    <th>description</th>
                    <th>is active</th>
                    <th>created date</th>
                    <th>updated date</th>
                    <th>actions</th>
                </tr>
            </thead>
             <tbody>
                @foreach($slides->items() as $key=>$slide)
                    @php
                        /** @var \App\Models\Slider $slide*/
                    @endphp
                    <tr>
                        <td>{{$key}}</td>
                        <td>
                            @unless(is_null($slide->thumbnail))
                                <img src="{{asset($slide->thumbnail)}}" alt="" style="width: 128px; height: 128px">
                            @else
                                <h6>no image</h6>
                            @endif
                        </td>
                        <td>
                            {{$slide->title}}
                        </td>
                        <td>
                            {{$slide->description}}
                        </td>
                        <td>
                            @if($slide->is_active)
                                Yes
                            @else
                                No
                            @endif
                        </td>
                        <td>
                            @unless(is_null($slide->created_at))
                                {{$slide->created_at}}
                                <hr>
                                {{$slide->jalali_created_at}}
                                <hr>
                                {{$slide->jalali_created_at->formatDifference()}}
                            @endunless
                            {{--
                            @unless(is_null($slide->created_at))
                                {{ $slide->created_at}}
                                <hr>
                                @php
                                    $timeStamp = strtotime($slide->created_at);
                                    $verta->setTimestamp($timeStamp);
                                @endphp
                                {{ $verta->formatDatetime() }}
                                <hr>
                                {{ $verta->formatDifference() }}
                            @endunless
                            --}}
                        </td>
                        <td>
                            @unless(is_null($slide->updated_at))
                                {{$slide->updated_at}}
                                <hr>
                                {{$slide->jalali_updated_at}}
                                <hr>
                                {{$slide->jalali_updated_at->formatDifference()}}
                            @endunless
                            {{--
                            @unless(is_null($slide->updated_at))
                                {{ $slide->updated_at }}
                                <hr>
                                @php
                                    $timeStamp = strtotime($slide->updated_at);
                                    $verta->setTimestamp($timeStamp);
                                @endphp
                                {{ $verta->formatDatetime() }}
                                <hr>
                                {{ $verta->formatDifference() }}
                            @endunless
                            --}}
                        </td>
                        <td>
                            <a href="{{ route('admin.slider.edit',$slide->id) }}">edit</a>
                            <form action="{{route('admin.slider.trash-slide',$slide->id)}}" method="post">
                                @method('DELETE')
                                @csrf
                                <button type="submit"> trash </button>
                            </form>
                            <a href="">
                                <form action="{{route('admin.slider.delete-slide',$slide->id)}}" method="post">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit"> Delete </button>
                                </form>
                            </a>
                        </td>
                    </tr>
                @endforeach
             </tbody>
        </table>
            {{ $slides->links("pagination::bootstrap-4") }}
        </section>
    @else
        <h1> no record found </h1>
    @endif
@endsection

resources/views/pages/admin/slider/trash-list.blade.php
@php
    /** @var \Illuminate\Pagination\LengthAwarePaginator $slides */
    $verta = verta();
@endphp
@extends('layouts.master')
@section('title')
    @parent | {{$title}}
@endsection
@section('body')
    @include('partials.message-printer')

    @if($slides->isNotEmpty())
        <section class="content">
            <h4>total : {{$slides->total()}}</h4>
            <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>thumbnail</th>
                    <th>title</th>
                    <th>description</th>
                    <th>is active</th>
                    <th>created date</th>
                    <th>updated date</th>
                    <th>deleted date</th>
                    <th>actions</th>
                </tr>
            </thead>
             <tbody>
                @foreach($slides->items() as $key=>$slide)
                    @php
                        /** @var \App\Models\Slider $slide*/
                    @endphp
                    <tr>
                        <td>{{$key}}</td>
                        <td>
                            @unless(is_null($slide->thumbnail))
                                <img src="{{asset($slide->thumbnail)}}" alt="" style="width: 128px; height: 128px">
                            @else
                                <h6>no image</h6>
                            @endif
                        </td>
                        <td>
                            {{$slide->title}}
                        </td>
                        <td>
                            {{$slide->description}}
                        </td>
                        <td>
                            @if($slide->is_active)
                                Yes
                            @else
                                No
                            @endif
                        </td>
                        <td>
                            {{--
                            @unless(is_null($slide->created_at))
                                {{ $slide->created_at }}
                                <hr>
                                @php
                                    $timeStamp = strtotime($slide->created_at);
                                    $verta->setTimestamp($timeStamp);
                                @endphp
                                {{ $verta->formatDatetime() }}
                                <hr>
                                {{ $verta->formatDifference() }}
                            @endunless
                             --}}
                            @unless(is_null($slide->created_at))
                                {{$slide->created_at}}
                                <hr>
                                {{$slide->jalali_created_at}}
                                <hr>
                                {{$slide->jalali_created_at->formatDifference()}}
                            @endunless
                        </td>
                        <td>
                            @unless(is_null($slide->updated_at))
                                {{$slide->updated_at}}
                                <hr>
                                {{$slide->jalali_updated_at}}
                                <hr>
                                {{$slide->jalali_updated_at->formatDifference()}}
                            @endunless
                            {{--
                            @unless(is_null($slide->updated_at))
                                {{ $slide->updated_at }}
                                <hr>
                                @php
                                    $timeStamp = strtotime($slide->updated_at);
                                    $verta->setTimestamp($timeStamp);
                                @endphp
                                {{ $verta->formatDatetime() }}
                                <hr>
                                {{ $verta->formatDifference() }}
                            @endunless
                            --}}
                        </td>
                        <td>
                            @unless(is_null($slide->deleted_at))
                                {{$slide->deleted_at}}
                                <hr>
                                {{$slide->jalali_deleted_at}}
                                <hr>
                                {{$slide->jalali_deleted_at->formatDifference()}}
                            @endunless
                            {{--
                            @unless(is_null($slide->deleted_at))
                                {{ $slide->deleted_at }}
                                <hr>
                                @php
                                    $timeStamp = strtotime($slide->deleted_at);
                                    $verta->setTimestamp($timeStamp);
                                @endphp
                                {{ $verta->formatDatetime() }}
                                <hr>
                                {{ $verta->formatDifference() }}
                            @endunless
                            --}}
                        </td>
                        <td>
                            <a href="{{ route('admin.slider.edit',$slide->id) }}">edit</a>
                            <a href="{{route('admin.slider.restore-slide',$slide->id)}}">restore </a>
                            <form action="{{route('admin.slider.delete-slide',$slide->id)}}" method="post">
                                @method('DELETE')
                                @csrf
                                <button type="submit"> Delete </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
             </tbody>
        </table>
            {{ $slides->links("pagination::bootstrap-4") }}
        </section>
    @else
        <h1> no record found </h1>
    @endif
@endsection